language: java
before_install:
  - bash dev/travis-before_install.sh

matrx:
   include:
       - arch: ppc64le
         jdk: 
            - openjdk8
            - openjdk11
         addons:
              apt:
                  packages:
                        - maven   

env:
  - HADOOP_PROFILE=default TEST_CODECS=uncompressed,brotli
  - HADOOP_PROFILE=default TEST_CODECS=gzip,snappy

install: mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true | pv -fbi 60 > mvn_install.log || (cat mvn_install.log && false)

before_script:
  - sed -i '181,224d' parquet-thrift/pom.xml 
  - sed -i '66 i <exclusions> \n <!-- hadoop-lzo is not required for parquet build/tests and there are issues downloading it --> \n \
		<exclusion> \n  <groupId>com.hadoop.gplcompression</groupId> \n <artifactId>hadoop-lzo</artifactId> \n \
		</exclusion> \n </exclusions>' parquet-thrift/pom.xml 

script: mvn verify --batch-mode javadoc:javadoc -P $HADOOP_PROFILE
