language: java
before_install:
  - bash dev/travis-before_install.sh

matrx:
   include:
       - arch: ppc64le
         jdk: 
            - openjdk8
            - openjdk11
         addons:
              apt:
                  packages:
                        - maven 
         before_script:
            - sed -i '441d' pom.xml
            - sed -i '441 i <version>2.19.1</version>' pom.xml
         script:
            - mvn test -e -P hadoop-1     

env:
  - HADOOP_PROFILE=default TEST_CODECS=uncompressed,brotli
  - HADOOP_PROFILE=default TEST_CODECS=gzip,snappy

install: mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true | pv -fbi 60 > mvn_install.log || (cat mvn_install.log && false)
script: mvn verify --batch-mode javadoc:javadoc -P $HADOOP_PROFILE
